In this file please write:

Experiment species name: latitude and longitude coordinates

+other infor from the paper that might be useful

The Exp. Species name refers to the name of the file as seen in the SRA file extractor master. 

If the specific longitude and latitude of the experiment are not available, please write the name of the city and country where the data was produced and the lat and long of that city in brackets.
EX: 

Experiment species name: city, country (latitude and longitude coordinates)

+other infor from the paper that might be useful

# DATA

- Paeonia_suffruticosa: 34°43′N	112°24′E

- Paeonia_rockii: 34°43′N	112°24′E

   V3-V4 hypervariable region of the bacterial 16S rRNA gene amplified using Bac 341f (5′-CCTACACGACGCTCTTCCGATCTN-3′) and Univ 805r (5′-GACTGGAGT TCCTTGGCACCCGAGAATTCCA-3′) primers

   each file is an individual sample. Note they are all diff cultivars of the same species!

- Oryza sativa: Kolkata, India (22.5726° N, 88.3639° E)
  
   V3-V4 hyper-variable region [V3 Forward Oligo: CCTACGGGNBGCASCAG and V4 Reverse Oligo: GACTACNVGGGTATCTAATCC] of 16S rDNA gene of bacteria and Archaea were used
 
- Chladophora: Beijin, China (40°29′9″N - 40°33′35″N)

- Cratoneuron: Beijin, China (40°29′9″N - 40°33′35″N)

- Pylaisiella: Beijin, China (40°29′9″N - 40°33′35″N)

- Bryum: Beijin, China (40°29′9″N - 40°33′35″N)

- Grimmia: Beijin, China (40°29′9″N - 40°33′35″N)

- Aloe: 3.235283 N, 101.568342 E

   V3–V4 conserved regions of 16S rRNA gene sequences in triplicate [31,22] using the 16S rRNA gene primers (forward primer 5ʹ-CCTACGGGNGGCWGCAG-3ʹ and reverse 5ʹ-GACTACHVGGGTATCTA-3ʹ)

- Zea: 39 N 116 E

   Some have high P some have low P. Consider this when you interpret results! 

- Quercus: Tennessee (36° 06' 11.3" N - 85° 50' 4.9" W), North Carolina (NC2)(35.722603 - -80.394309), North Carolina (NC3)(35° 48' 11.1" N - 80° 33' 25.0" W)
   Three species in dataset - Quercus phellos, Pinus taeda, & Populus deltoides
   Experimental design - sterile seedlings of each species planted in soil collected from each of three locations to see if endophyte      communities that colonize each seedling are consistent with the soil type











