#!/bin/bash
#SBATCH -c 12
#SBATCH --time=1-10:00:00
#SBATCH --job-name=SRR_Hannah
#SBATCH --mail-type=ALL
#SBATCH --mail-user=h_driver23@hotmail.com
#SBATCH --error=SRA_HannahSRR.err

module load sra-toolkit

cd /global/home/sa104007/EndophytePRJ/Pinus
fastq-dump --accession SRR3742197
fastq-dump --accession SRR3742194
fastq-dump --accession SRR3742193
fastq-dump --accession SRR3742191
fastq-dump --accession SRR3742190
fastq-dump --accession SRR3742184
fastq-dump --accession SRR3742182
fastq-dump --accession SRR3742180
fastq-dump --accession SRR3742179
fastq-dump --accession SRR3742177
fastq-dump --accession SRR3742176
fastq-dump --accession SRR3742138

cd ../Brassica_napus
for ((i = 51; i<= 98; i++)); do fastq-dump --accession SRR54397$i; done

cd ../Brassica_oleracea
for ((i = 24; i<= 47; i++)); do fastq-dump --accession SRR51859$i; done

