#!/bin/bash
#SBATCH -c 12
#SBATCH --time=1-10:00:00
#SBATCH --job-name=SRA_2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=h_driver23@hotmail.com
#SBATCH --error=SRA_2.err

cd /global/home/sa104007/EndophytePRJ/Chladophora
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2311710
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2311709
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2311688	
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2311687
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2310747
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2310447
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2310446	
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2310445
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2269390
/global/home/sa104007/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0 --accession SRX2230043

cd ../Cratoneuron
for ((i = 32; i<= 55; i++)); do "/global/home/sa104006/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0" --accession SRX25019$i$; done

for ((i = 32; i<= 55; i++)); do "/global/home/sa104006/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0" --accession SRX25019$i$; done

for ((i = 32; i<= 55; i++)); do "/global/home/sa104006/SRA/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump.2.9.0" --accession SRX25019$i$; done

