#!/bin/bash
#SBATCH -c 12
#SBATCH --time=1-10:00:00
#SBATCH --job-name=SRA_2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=h_driver23@hotmail.com
#SBATCH --error=SRA_2.err

module load sra-toolkit

cd /global/home/sa104007/EndophytePRJ/Chladophora
fastq-dump --accession SRR4734837

cd ../Cratoneuron
fastq-dump --accession SRR4734815

cd ../Pylaisiella
fastq-dump --accession SRR4708713

cd ../Bryum
fastq-dump --accession SRR4706101

cd ../Grimmia
fastq-dump --accession SRR4453815

cd ../Aloe
fastq-dump --accession SRR2204709	
fastq-dump --accession SRR2204707
fastq-dump --accession SRR2204344	
fastq-dump --accession SRR2204159

cd ../Zea
fastq-dump --accession SRR5052006
fastq-dump --accession SRR5052004
fastq-dump --accession SRR5052003		
fastq-dump --accession SRR5052001
fastq-dump --accession SRR5052000
fastq-dump --accession SRR5051999
fastq-dump --accession SRR5051568		
fastq-dump --accession SRR5051567
fastq-dump --accession SRR5051415
fastq-dump --accession SRR5051407
fastq-dump --accession SRR5051401		
fastq-dump --accession SRR5051400

cd ../Oryza
fastq-dump --accession SRR5211361
fastq-dump --accession SRR5211360

cd ../Paeonia_suffruticosa
fastq-dump --accession SRR4289224	
fastq-dump --accession SRR4289222
fastq-dump --accession SRR4289220	
fastq-dump --accession SRR4289218
fastq-dump --accession SRR4289217
fastq-dump --accession SRR4289215
fastq-dump --accession SRR4267992	
fastq-dump --accession SRR4267988
fastq-dump --accession SRR4267987
fastq-dump --accession SRR4267985
fastq-dump --accession SRR4265353	
fastq-dump --accession SRR4265352

cd ../Paeonia_rockii
fastq-dump --accession SRR4289219
fastq-dump --accession SRR4289223
fastq-dump --accession SRR4267986	
fastq-dump --accession SRR4263477
