#!/bin/bash
#SBATCH -c 12
#SBATCH --time=1-10:00:00
#SBATCH --job-name=Trimmomatic
#SBATCH --mail-type=ALL
#SBATCH --mail-user=h_driver23@hotmail.com
#SBATCH --error=Trimmomatic_3.err

module load trimmomatic

cd ./Chladophora
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Brassica_napus
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Brassica_oleracea
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Populus
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Cratoneuron
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Pylaisiella
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDINGW$

cd ../Bryum
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Grimmia
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Aloe
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Zea
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Oryza
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Paeonia_suffruticosa
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Paeonia_rockii
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Pinus
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Orchid
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Pinus_flexilis
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Solanum
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Espeletia
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Vitis
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Santiria
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Microdesmis
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$

cd ../Rothmannia
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.36.jar SE -phred33 *.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDI$
